name: cd

on: [push, pull_request]

env:
  DEV_DESCRIPTION: ${{ secrets.DEV_DESCRIPTION }}
  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}
  BASE_URL: ${{ secrets.BASE_URL }}
  NOTION_TABLE_ID: ${{ secrets.NOTION_TABLE_ID }}
  NOTION_ABOUT_PAGE_ID: ${{ secrets.NOTION_ABOUT_PAGE_ID }}
  GHUB_USERNAME: ${{ secrets.GHUB_USERNAME }}
  DEV_LOGO: ${{ secrets.DEV_LOGO }}
  DEV_NAME: ${{ secrets.DEV_NAME }}
  DEV_ROLE: ${{ secrets.DEV_ROLE }}
  DEV_GITHUB_LINK: ${{ secrets.DEV_GITHUB_LINK }}
  DEV_TWITTER_LINK: ${{ secrets.DEV_TWITTER_LINK }}
  DEV_LINKEDIN_LINK: ${{ secrets.DEV_LINKEDIN_LINK }}

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist